apiVersion: "apps/v1"
kind: "Deployment"

metadata:
  name: "excalidraw-oauth2-proxy"
  namespace: "excalidraw"

  annotations:
    downscaler/exclude: "true"

  labels:
    application: "excalidraw-oauth2-proxy"

spec:
  replicas: 1

  selector:
    matchLabels:
      application: "excalidraw-oauth2-proxy"

  template:

    metadata:

      labels:
        application: "excalidraw-oauth2-proxy"

    spec:

      containers:

        - name: "service"
          image: "{{{OAUTH2_PROXY_IMAGE}}}"

          ports:
            - containerPort: 4180
              protocol: "TCP"

          resources:
            limits:
              memory: "1000Mi"
            requests:
              cpu: "100m"
              memory: "1000Mi"
          env:
            - name: "OAUTH2_PROXY_CLIENT_ID"
              valueFrom:
                secretKeyRef:
                  name: excalidraw-client
                  key: client
            - name: "OAUTH2_PROXY_CLIENT_SECRET"
              valueFrom:
                secretKeyRef:
                  name: excalidraw-client
                  key: client_secret

            - name: "OAUTH2_PROXY_UPSTREAM"
              value: http://excalidraw-room.excalidraw/socket.io/,http://excalidraw.excalidraw/

            - name: "OAUTH2_PROXY_UPSTREAMS"
              value: http://excalidraw-room.excalidraw/socket.io/,http://excalidraw.excalidraw/

            - name: "OAUTH2_PROXY_REDIRECT_URL"
              value: "https://<yourdomain>/oauth2/callback"

            - name: "OAUTH2_PROXY_EMAIL_DOMAINS"
              value: "<your email domain>"
            
            - name: "OAUTH2_PROXY_PROVIDER"
              value: "google"
            
            # should be a secret
            - name: "OAUTH2_PROXY_COOKIE_SECRET"
              value: "<yoursecret>"

            - name: "OAUTH2_PROXY_HTTP_ADDRESS"
              value: ":4180"